# Generated by Django 5.0.7 on 2024-07-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hotel_id", models.IntegerField()),
                (
                    "period",
                    models.CharField(
                        choices=[("month", "Monthly"), ("day", "Daily")], max_length=10
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField(blank=True, null=True)),
                ("day", models.IntegerField(blank=True, null=True)),
                ("booking_count", models.IntegerField()),
            ],
        ),
    ]
