# Generated by Django 5.0.7 on 2024-07-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboarddata",
            name="cancellation_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="dashboarddata",
            unique_together={("hotel_id", "period", "year", "month", "day")},
        ),
    ]
