# Generated by Django 5.0.7 on 2024-08-02 10:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "hotel_id",
                    models.IntegerField(
                        help_text="The ID of the hotel where the event took place."
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="The date and time when the event was recorded."
                    ),
                ),
                (
                    "rpg_status",
                    models.IntegerField(
                        choices=[(1, "Booking"), (2, "Cancellation")],
                        help_text="The status of the event, either booking or cancellation.",
                    ),
                ),
                (
                    "room_reservation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="A unique identifier for the room reservation.",
                    ),
                ),
                (
                    "night_of_stay",
                    models.DateField(
                        help_text="The date of stay for which the event is booked or canceled."
                    ),
                ),
            ],
        ),
    ]
