# Generated by Django 5.0.7 on 2024-07-31 12:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="room_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
