# Generated by Django 5.0.7 on 2024-07-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_provider", "0002_alter_event_room_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="room_id",
            new_name="room_reservation_id",
        ),
    ]
